### PR TITLE
chore(projects): update InstantSearch.js entry

### PR DESCRIPTION
**Pull request by bobylito**
We've published the new V2 version :rocket:

### CODE REVIEW

**Comment by vvo** [comment]
Still shows lowercase, weird, maybe a caching/web worker issue? cc @JonasBa 
image

**Comment by bobylito** [comment]
> Still shows lowercase, weird, maybe a caching/web worker issue? cc @JonasBa

I don't think the index has been updated yet. Maybe it's that.

**Comment by bobylito** [comment]
Does anyone know how it get deployed? Magic on merge?

**Comment by Haroenv** [comment]
I think it's deployed on merge, @JonasBa knows

**Comment by vvo** [comment]
Oh Ok then let's just merge this and see what happens?

**Comment by bobylito** [comment]
> Oh Ok then let's just merge this and see what happens?

🚀

**Comment by bobylito** [comment]
No luck :(

**Pull request merged**
